name: espressoblochive
description: "EspressoBlocHive"

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #For Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  intl_utils: ^2.8.7

  #For Services locator
  get_it: ^7.6.4

  #For State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  #For Local Storage
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0

  #For Gen Models
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

  #For https services
  retrofit: ^4.0.3
  retrofit_generator: ^8.1.0
  dio: ^5.3.3
  dio_cache_interceptor: ^3.4.4
  dio_cookie_manager: ^3.1.1
  dio_http2_adapter: ^2.3.1+1
  dio_smart_retry: ^6.0.0
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.1


  #For FireBase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_auth: ^4.16.0

  #For Notification
  flutter_local_notifications: ^17.1.2
  flutter_app_badger: ^1.5.0


  #For Ui
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.2
  image_picker: ^1.0.5
  scrollable_positioned_list: ^0.3.8
  auto_size_text: ^3.0.0-nullsafety.0
  circular_reveal_animation: ^2.0.0

  #Others
  path_provider: ^2.1.2
  path: ^1.8.0
  crypto: ^3.0.3
  logger: ^2.1.0
  animated_bottom_navigation_bar: ^1.3.3
  flex_color_scheme: ^7.3.1
  remixicon: ^1.2.0
  iconly: ^1.0.1
  hive: ^2.2.3
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  alert_banner: ^1.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.2


dependency_overrides:
  intl: ^0.19.0
  meta: 1.14.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true